//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewHouseEntities : DbContext
    {
        public NewHouseEntities()
            : base("name=NewHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NH_Contact> NH_Contact { get; set; }
        public virtual DbSet<NH_Feature> NH_Feature { get; set; }
        public virtual DbSet<NH_Homepage> NH_Homepage { get; set; }
        public virtual DbSet<NH_Intro> NH_Intro { get; set; }
        public virtual DbSet<NH_News> NH_News { get; set; }
        public virtual DbSet<NH_Project> NH_Project { get; set; }
        public virtual DbSet<NH_Solution> NH_Solution { get; set; }
        public virtual DbSet<NH_AboutUs> NH_AboutUs { get; set; }
        public virtual DbSet<NH_Partner> NH_Partner { get; set; }
        public virtual DbSet<NH_Partnership> NH_Partnership { get; set; }
        public virtual DbSet<NH_Slider> NH_Slider { get; set; }
        public virtual DbSet<NH_Architec> NH_Architec { get; set; }
    }
}
