//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NH_Feature
    {
        public int ID { get; set; }
        public string Icon01 { get; set; }
        public string Title01 { get; set; }
        public string Description01 { get; set; }
        public string Icon02 { get; set; }
        public string Title02 { get; set; }
        public string Description02 { get; set; }
        public string Icon03 { get; set; }
        public string Title03 { get; set; }
        public string Description03 { get; set; }
        public string Icon04 { get; set; }
        public string Title04 { get; set; }
        public string Description04 { get; set; }
        public string Icon05 { get; set; }
        public string Title05 { get; set; }
        public string Description05 { get; set; }
        public string Icon06 { get; set; }
        public string Title06 { get; set; }
        public string Description06 { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
    }
}
