//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NH_Homepage
    {
        public int ID { get; set; }
        public string Title01 { get; set; }
        public string Description { get; set; }
        public string SubTitle01 { get; set; }
        public string Image01 { get; set; }
        public string Description01 { get; set; }
        public string SubTitle02 { get; set; }
        public string Image02 { get; set; }
        public string Description02 { get; set; }
        public string SubTitle03 { get; set; }
        public string Image03 { get; set; }
        public string Description03 { get; set; }
        public string SubTitle04 { get; set; }
        public string Image04 { get; set; }
        public string Description04 { get; set; }
        public string Language { get; set; }
    }
}
