//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NH_Project
    {
        public string ID { get; set; }
        public string ProjectName { get; set; }
        public string Avatar { get; set; }
        public string Images { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
        public Nullable<int> ArchitectID { get; set; }
    }
}
