//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NH_Slider
    {
        public int ID { get; set; }
        public string Title01 { get; set; }
        public string SubTitle01 { get; set; }
        public string Image01 { get; set; }
        public string Title02 { get; set; }
        public string SubTitle02 { get; set; }
        public string Image02 { get; set; }
        public string Title03 { get; set; }
        public string SubTitle03 { get; set; }
        public string Image03 { get; set; }
        public string Title04 { get; set; }
        public string SubTitle04 { get; set; }
        public string Image04 { get; set; }
        public string Title05 { get; set; }
        public string SubTitle05 { get; set; }
        public string Image05 { get; set; }
        public string Title06 { get; set; }
        public string SubTitle06 { get; set; }
        public string Image06 { get; set; }
    }
}
